# fly.toml app configuration file generated for rtt-alhuda on 2026-05-24T23:10:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rtt-alhuda'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  RTT_ALHUDA_LISTEN_HOST = '0.0.0.0'
  RTT_ALHUDA_LISTEN_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 80
    soft_limit = 50

  [http_service.http_options]
    idle_timeout = 7200

  [[http_service.checks]]
    interval = '30s'
    timeout = '15s'
    grace_period = '2m0s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
